import Link from "next/link";

const resources = [
  { label: "Familias · ejemplo", title: "Conversaciones que abren caminos", text: "Ideas para acompañar momentos de tarea sin convertirlos en una pelea.", color: "#8aa59a" },
  { label: "Docentes · ejemplo", title: "Observar para acompañar", text: "Una guía breve para registrar procesos de aprendizaje cotidianos.", color: "#e2b88a" },
  { label: "Organización · ejemplo", title: "Un rato posible", text: "Propuestas simples para construir rutinas flexibles y sostenibles.", color: "#c8a8bb" },
];

export default function Home() {
  return <>
    <section className="shell hero">
      <div><p className="kicker">Psicopedagogía · Bahía Blanca + online</p><h1>Encontrar una forma propia de <span className="serif">aprender.</span></h1><p className="lead">Un espacio para mirar lo que está pasando, ordenar preguntas y construir próximos pasos con acompañamiento humano.</p><div className="hero-actions"><Link href="/reservar" className="button coral">Reservar turno <span aria-hidden="true">↗</span></Link><Link href="/recursos" className="button secondary">Explorar recursos</Link></div></div>
      <div className="route-map" aria-label="Cómo es el acompañamiento"><p className="kicker">Una ruta posible</p><div className="route-title">No hay una única manera de llegar.</div><div className="route-list"><div className="route-step"><span>01</span><p>Escuchamos la situación y lo que necesitás hoy.</p></div><div className="route-step"><span>02</span><p>Miramos juntos qué estrategias ya existen.</p></div><div className="route-step"><span>03</span><p>Probamos pequeños cambios que tengan sentido.</p></div></div></div>
    </section>
    <section className="section dark" id="acompanamiento"><div className="shell split"><div className="text-block"><p className="kicker">El vínculo primero</p><h2>Aprender también es sentirse acompañado.</h2><p>La psicopedagogía puede abrir un espacio para comprender cómo aprende cada persona, qué la ayuda y qué necesita ser escuchado. El trabajo se construye con la persona y, cuando corresponde, junto a su familia y otros referentes.</p><Link href="/acompanamiento" className="button coral">Conocer el proceso</Link></div><div className="steps"><div className="step-row"><span className="step-num">A</span><div><h3>Una mirada singular</h3><p>Partimos de la historia y la experiencia concreta, sin recetas universales.</p></div></div><div className="step-row"><span className="step-num">B</span><div><h3>Una conversación clara</h3><p>Traducimos preocupaciones en preguntas posibles, sin etiquetar de más.</p></div></div><div className="step-row"><span className="step-num">C</span><div><h3>Un camino compartido</h3><p>Revisamos lo que funciona y ajustamos el acompañamiento con el tiempo.</p></div></div></div></div></section>
    <section className="section" id="sobre-mi"><div className="shell split"><div><p className="kicker">Sobre este espacio</p><h2>Un lugar para pensar con alguien.</h2></div><div className="text-block"><p>Hola. Soy <strong>[nombre profesional pendiente]</strong>, psicopedagoga. Este texto es una presentación de ejemplo para que puedas reemplazarlo por la trayectoria, matrícula y enfoque que quieras comunicar.</p><p>La propuesta busca acompañar procesos de aprendizaje a lo largo de la vida con una escucha atenta, objetivos posibles y diálogo con las personas que forman parte de cada recorrido.</p><div className="notice">La foto, nombre, título exacto, matrícula, edades y públicos de atención están pendientes de validación profesional.</div></div></div></section>
    <section className="section tinted"><div className="shell"><div className="section-head"><div><p className="kicker">Para seguir explorando</p><h2>Recursos para el día a día.</h2></div><p>Materiales digitales de ejemplo para acompañar conversaciones, observaciones y rutinas. No reemplazan una consulta individual.</p></div><div className="resource-grid">{resources.map((r) => <article className="resource-card" key={r.title}><div className="resource-cover" style={{ background:r.color }}>{r.title}</div><span className="tag">{r.label}</span><p>{r.text}</p><span className="price">Precio a confirmar</span></article>)}</div><div className="hero-actions"><Link href="/recursos" className="button secondary">Ver catálogo completo</Link></div></div></section>
    <section className="section"><div className="shell"><p className="kicker">Preguntas frecuentes</p><h2>Antes de dar el próximo paso.</h2><div className="faq-list"><details><summary>¿Cómo sé si este espacio puede ayudarme?</summary><p>Podés escribir o reservar una primera conversación para contar brevemente qué te preocupa. No hace falta llegar con un diagnóstico ni saber exactamente qué pedir.</p></details><details><summary>¿La atención puede ser online?</summary><p>La modalidad online está contemplada en el circuito de reservas. La disponibilidad, edades, servicios y valores son datos pendientes de confirmar por la profesional.</p></details><details><summary>¿Puedo consultar por otra persona?</summary><p>Si la consulta es por una persona menor de edad, la reserva debe realizarla su madre, padre o responsable adulto. Evitá compartir información sensible en el formulario inicial.</p></details></div></div></section>
  </>;
}
