"use client";
import { FormEvent, useState } from "react";

const slots = ["09:00", "10:30", "14:00", "15:30", "17:00"];
export function BookingForm() {
  const [date, setDate] = useState(""); const [slot, setSlot] = useState(""); const [mode, setMode] = useState("online"); const [loading, setLoading] = useState(false); const [result, setResult] = useState<{ok:boolean; message:string}|null>(null);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setLoading(true); setResult(null); const data = new FormData(e.currentTarget); const response = await fetch("/api/bookings", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify(Object.fromEntries(data)) }); const body = await response.json(); setLoading(false); setResult({ok:response.ok, message:body.message}); if(response.ok) e.currentTarget.reset(); }
  return <div className="form-layout"><form className="form-panel" onSubmit={submit}>
    {result && <div className={`status ${result.ok ? "" : "error"}`} role="status">{result.message}</div>}
    <h2>Solicitar turno</h2><p className="field-help">Solo pedimos datos para coordinar. No compartas diagnósticos ni historia clínica por este medio.</p>
    <div className="field"><label htmlFor="service">Motivo general</label><select id="service" name="service" required defaultValue=""><option value="" disabled>Elegí una opción</option><option>Primera conversación</option><option>Acompañamiento psicopedagógico</option><option>Consulta de orientación a familia</option></select><span className="field-help">Opciones de ejemplo, pendientes de validar.</span></div>
    <fieldset className="field"><legend>Modalidad</legend><div className="choice-grid"><label className="choice"><input type="radio" name="mode" value="online" checked={mode === "online"} onChange={e=>setMode(e.target.value)} /> Online</label><label className="choice"><input type="radio" name="mode" value="presencial" checked={mode === "presencial"} onChange={e=>setMode(e.target.value)} /> Presencial</label></div></fieldset>
    <div className="form-row"><div className="field"><label htmlFor="date">Fecha</label><input id="date" name="date" type="date" required min={new Date().toISOString().slice(0,10)} value={date} onChange={e=>setDate(e.target.value)} /></div><div className="field"><label htmlFor="slot">Horario</label><select id="slot" name="slot" required value={slot} onChange={e=>setSlot(e.target.value)}><option value="">Elegí</option>{slots.map(s=><option key={s}>{s}</option>)}</select></div></div>
    <div className="field"><label htmlFor="name">Nombre de quien consulta</label><input id="name" name="name" required minLength={2} placeholder="Nombre y apellido" /></div><div className="field"><label htmlFor="email">Correo de contacto</label><input id="email" name="email" type="email" required placeholder="nombre@correo.com" /></div><div className="field"><label htmlFor="phone">WhatsApp (opcional)</label><input id="phone" name="phone" inputMode="tel" placeholder="Código de área + número" /></div><div className="field"><label htmlFor="adult">¿La reserva es para una persona menor de edad?</label><select id="adult" name="adult" required defaultValue=""><option value="" disabled>Elegí una opción</option><option value="yes">Sí, soy responsable adulto</option><option value="no">No</option></select></div><div className="field"><label htmlFor="note">Mensaje breve (opcional)</label><textarea id="note" name="note" rows={3} maxLength={300} placeholder="¿Qué te gustaría conversar? Sin datos sensibles, por favor." /></div><button className="button coral" disabled={loading}>{loading ? "Enviando solicitud…" : "Solicitar este horario"}</button>
  </form><aside className="summary-box"><p className="kicker">Tu selección</p><h2 style={{color:"#fffdf8"}}>Un próximo paso, sin apuro.</h2><dl><div><dt>Modalidad</dt><dd>{mode === "online" ? "Online" : "Presencial"}</dd></div><div><dt>Fecha</dt><dd>{date || "A definir"}</dd></div><div><dt>Horario</dt><dd>{slot || "A definir"}</dd></div></dl><p style={{color:"#cad9df",fontSize:".9rem"}}>La solicitud no confirma automáticamente el turno. La profesional debe revisarla y confirmar disponibilidad.</p></aside></div>;
}
